import Head from 'next/head'
import Image from 'next/image'
import classes from '../styles/Home.module.scss';
import { useState, useEffect } from 'react';
import { Table } from 'antd';
import { useRouter } from 'next/router';

const Home = ({ data }) => {

  const router = useRouter();

  const columns = [
    {
      title: 'ID',
      dataIndex: `_id`,
      key: 'id',
      render:(text,record,index) => text.slice(text.length - 8),
    },
    {
      title: 'Username',
      dataIndex: 'username',
      key: 'username',
      sorter: (a,b) => a.username.localeCompare(b.username),
    },
    {
      title: 'Email',
      dataIndex: 'email',
      key: 'email',
      sorter: (a,b) => a.email.localeCompare(b.email),
    },
    {
      title: 'First Name',
      dataIndex: 'firstName',
      key: 'firstName',
      sorter: (a,b) => a.firstName.localeCompare(b.firstName),
    },
    {
      title: 'Last Name',
      dataIndex: 'lastName',
      key: 'lastName',
      sorter: (a,b) => a.lastName.localeCompare(b.lastName),
    },
  ]



  return (
    <div className={classes.container}>
      <Head>
        <title>Adelphic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={classes.tableContainer}>
        <Table
          columns={columns}
          dataSource={data}
          rowKey={data.username}
          onRow={(record, rowIndex) => {
            return {
              onClick: () => router.push({
                pathname: '/edit',
                query: { data: record._id }
              }),
            };
          }}
        />
      </div>
    </div>
  )
}

export default Home;

export async function getServerSideProps(context) {
  const res = await fetch('http://localhost:3000/api/users');
  const { data } = await res.json();

  return {
    props: {
      data
    }
  }
}